### ISSUE TITLE
Not intuitive error log if the class templates mapping does not match with ttl model

### ISSUE THREAD

**Issue by RohanAsmat** [white-gecko/jekyll-rdf#100] opened 2017-08-01 11:36 UTC
I think its a good idea to report it in a programmer friendly way that if you have a missing class in your graph that you are trying to map using class template, error log can be more programmer friendly.

For now it was something like this:

```sh
undefined method propogate template  for Nil:nilclass
```
Though it states the problem but the following could be more clear:

```sh
No such class in your graph: example.ttl
```
or

```sh
Class_instance_mapping does not corresponds with any class in example.ttl
```

Or something more clear, based on the developers understanding. #

**Comment by white-gecko** [comment] 2017-08-01 12:19
This is a duplicate of #97

**Closed** 2017-08-01 12:20 UTC
Labels: duplicate
